version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
    - "5440:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: nopassword
  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-alpha.10
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:nopassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  graphql-engine-old:
    image: hasura/graphql-engine:v1.3.3
    ports:
    - "8081:8080"
    depends_on:
    - "postgres"
    restart: always
    volumes:
      - ./old-data-migrations/migrations:/hasura-migrations
      - ./old-data-migrations/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:nopassword@postgres-old:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  postgres-old:
    image: postgres:12
    restart: always
    ports:
    - "5460:5432"
    volumes:
    - db_old_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: nopassword
volumes:
  db_data:
  db_old_data:
